### ISSUE TITLE
ValueError: cannot convert float NaN to integer - after Start of calculating target positions.

### ISSUE THREAD

**Issue by robby28-11** [brndnmtthws/thetagang#368]
Thetagang gets portfolio positions but the it kind of crashes. Was working wonderful, haven't changed anything. Wonder what might have influenced this. Already switched back to 1.9.1 and 1.9.2 with the same issue.

Any ideas?

`│ T   │   │     │     │     │     │      │     │      │     │      │     │     │
│     │ P │  -1 │ $0… │ $0… │ $-0 │  $-2 │  $2 │ 90.… │ $1… │ 202… │   2 │     │
│     │ P │  -5 │ $0… │ $0… │ $-… │ $-98 │ $41 │ 41.… │ $1… │ 202… │  65 │     │
└─────┴───┴─────┴─────┴─────┴─────┴──────┴─────┴──────┴─────┴──────┴─────┴─────┘
Calculating target positions... ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━   0% -:--:--
╭───────────────────── Traceback (most recent call last) ──────────────────────╮
│ /usr/local/lib/python3.10/dist-packages/thetagang/portfolio_manager.py:591   │
│ in manage                                                                    │
│                                                                              │
│    588 │   │   │   │   positions_table,                                      │
│    589 │   │   │   │   put_actions_table,                                    │
│    590 │   │   │   │   puts_to_write,                                        │
│ ❱  591 │   │   │   ) = self.check_if_can_write_puts(account_summary, portfol │
│    592 │   │   │                                                             │
│    593 │   │   │   # Look for lots of stock that don't have covered calls    │
│    594 │   │   │   (call_actions_table, calls_to_write) = self.check_for_unc │
│                                                                              │
│ /usr/local/lib/python3.10/dist-packages/thetagang/portfolio_manager.py:1005  │
│ in check_if_can_write_puts                                                   │
│                                                                              │
│   1002 │   │   │   targets[symbol] = round(                                  │
│   1003 │   │   │   │   self.config["symbols"][symbol]["weight"] * total_buyi │
│   1004 │   │   │   )                                                         │
│ ❱ 1005 │   │   │   self.target_quantities[symbol] = math.floor(              │
│   1006 │   │   │   │   targets[symbol] / ticker.marketPrice()                │
│   1007 │   │   │   )                                                         │
│   1008                                                                       │
╰──────────────────────────────────────────────────────────────────────────────╯
ValueError: cannot convert float NaN to integer

** Press ANY KEY to close this window ** `

**Comment by brndnmtthws** [comment]
Was the market open when you ran this? The ticker is not returning a price, hence the error.

**Comment by robby28-11** [comment]
Yes. Also at this moment same error. Even with 1.8.1

**Comment by brndnmtthws** [comment]
Odd. Does IBKR return a price for the same symbol? There are some weird edge cases (like things with very low liquidity) where sometimes it doesn't return data. It should normally return the midpoint price, or the last trade price if that's not available. This is a tricky case because it's not safe to keep going if you can't get a valid price for the symbol, it will lead to undefined behaviour.

See here: https://ib-insync.readthedocs.io/api.html#ib_insync.ticker.Ticker.marketPrice

**Comment by robby28-11** [comment]
Argh, yes there was one option with a price of 0.00. Just bought it for 0.01 to close that position. Fixed the issue instantly. Thanks for the hint.

**Comment by robby28-11** [comment]
The put option (T Feb16 14Put) was sold with a very low commission. Unfortunately, I hadn't used minimum_credit yet, which could probably have prevented it. As a result, the option was very far out of the money.

Of course, the option would have simply expired - that's not a problem. The problem, however, is that all other options were set to "pause" because the script was always interrupted as a result.

So maybe it's not such a bad idea to distinguish whether the option price is 0.00 or does not return a value at all?

**Comment by brndnmtthws** [comment]
What's especially confusing to me is that it's actually failing on getting the market price for the _stock_, not the option itself. That should certainly not be returning 0 or NaN. It _should_ already gracefully handle cases where the option has no price, usually it'll print an error and continue anyway.

So, I'm either failing to understand the problem, or I've missed some key piece of information.

Was there any other detail in the stack trace from before? I'm thinking that stack trace is actually a red herring and the error is somewhere else.

If I were to guess, it's failing after this function (which tries to handle this as gracefully as possible, but could still return a 0 or NaN in some cases): https://github.com/brndnmtthws/thetagang/blob/42af12345fc7bf77ae0dfc0db57c1f89c5cf6089/thetagang/util.py#L207-L222

The error itself is caused by a failed type conversion from a float to an integer, which doesn't quite make sense because the prices are handled as floats. I will make a tiny correction so that in the case that `ticker.marketPrice()` is NaN, it'll return 0.0 instead.

**Comment by brndnmtthws** [comment]
One of those two values (either the market price, or the weights) has to be NaN. It's not the weight, because it prints that earlier (showing 20%), so it must be the market price.

What do you have this setting set to: https://github.com/brndnmtthws/thetagang/blob/dfd37f43a4ee789c6e7afe8771d2f91a18db016f/thetagang.toml#L386

The only thing I can think of, is that if `ib_insync.api_response_wait_time` is too small, it won't wait long enough for the API to get the market prices. Anything less than 5 is probably going to frequently cause problems.

In any case, I'll make one more tweak to this code, which will hopefully handle this situation better.

**Comment by robby28-11** [comment]
api_response_wait_time = 60

for both paper/live
